config/routes.rb
Rails.application.routes.draw do
  root 'random_books#new'
  get '/random', to: 'random_books#new'
  post '/random',to: 'random_books#create'
  resources :random_books, only:[:index,:show,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/random_book.rb
class RandomBook < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/random_books_controller.rb
class RandomBooksController < ApplicationController
  include GoogleBooksApi

  def new
    book = RandomBook.last
    now = Time.current
    if book && book.created_at.day == now.day
      @book = book
    else
      @book = nil
    end
  end

  def index
    @books = RandomBook.all
  end

  def show
    @book = RandomBook.find(params[:id])
  end

  def create
    if params[:random_books][:keyword].present?
      keyword = params[:random_books][:keyword]
      url = url_from_keyword(keyword)
      json = get_json_from_url(url)
      @book = {}
      if items = json['items']
        ram = rand(19)
        @book = items[ram]
        if book_create(@book)
          redirect_to random_url
        else
          flash.now[:danger] = "本を保存できませんでした。"
          redirect_to random_url
        end
      else
        flash.now[:danger] = "該当する本がありません"
        render 'new'
      end
    else
      flash.now[:danger] = "キーワードが空です。"
      render 'new'
    end
  end

  def destroy
    RandomBook.find(params[:id]).destroy
    redirect_to random_books_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/random_books_helper.rb
module RandomBooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomBookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/random_books/index.html.erb
<div class="books">
  <%= link_to "今日の本を決めるに戻る", random_path, method: :get %>
  <% @books.each do |book| %>
    <div class="book">
      <p><%= book.created_at.year %>年<%= book.created_at.month %>月<%= book.created_at.day %>日の本</p>
      <%= book.title %>
      <%= link_to image_tag(book.img),random_book_path(book) %>
      <%= link_to "delete", random_book_path(book) , method: :delete,
                                      data: { confirm: "本当によろしいですか？" } %>
    </div>

  <% end %>
</div>

app/views/random_books/new.html.erb
<%= link_to "履歴を見る", random_books_path, method: :get %>
<h1>本日の本を決めよう！</h1>
<% if @book %>
  <p>今日の本</p>
  <%= @book.title %>
  <%= link_to image_tag(@book.img),random_book_path(@book) %>
<% end %>
<%= form_for(:random_books , url: random_path)  do |f| %>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
  <%= f.label :キーワードを入力してください %>
  <%= f.text_field :keyword %>
  <%= f.submit "今日の本を決める" %>
<% end %>

app/views/random_books/show.html.erb
<% if @book %>
<p>この本について</p>
<%= @book.title %>
<% end %>